
from PySide2.QtCore import *
from PySide2.QtWidgets import *
from PySide2.QtGui import *
import os
import netifaces
import requests

class Widget1(QWidget):
    def __init__(self, parent=None):
        super(Widget1, self).__init__(parent)
        self.gui()

    def gui(self):
        self.w1 = self
        self.w1.setAutoFillBackground(True)
        self.w1.setWindowTitle("")
        self.w1.resize(500, 450)
        self.w1.setCursor(Qt.ArrowCursor)
        self.w1.setToolTip("")
        self.tab1 = QTabWidget(self.w1)
        self.tab1.move(0, 0)
        self.tab1.resize(500, 450)
        self.tab1.setTabPosition(QTabWidget.North)
        self.tab1.setCursor(Qt.ArrowCursor)
        self.tab1.setToolTip("")
        self.ta1 = QWidget(self.tab1)
        self.ta1.setAutoFillBackground(True)
        self.ta1.setWindowTitle("")
        self.ta1.move(0, 0)
        self.ta1.resize(496, 423)
        self.ta1.setCursor(Qt.ArrowCursor)
        self.ta1.setToolTip("")
        self.label17 = QLabel(self.ta1)
        self.label17.setText("Welcome To NetWarrior")
        self.label17.move(18, 16)
        self.label17.resize(130, 22)
        self.label17.setCursor(Qt.ArrowCursor)
        self.label17.setToolTip("")
        self.label18 = QLabel(self.ta1)
        self.label18.setText("i designed this tool to help people who stuck in countries without freedom of speech (like iran)")
        self.label18.move(18, 56)
        self.label18.resize(460, 22)
        self.label18.setCursor(Qt.ArrowCursor)
        self.label18.setToolTip("")
        self.label19 = QLabel(self.ta1)
        self.label19.setText("this tool can help them bypass internet censorship and get better internet connection")
        self.label19.move(18, 76)
        self.label19.resize(420, 22)
        self.label19.setCursor(Qt.ArrowCursor)
        self.label19.setToolTip("")
        self.tab1.addTab(self.ta1, "Home")
        self.ta2 = QWidget(self.tab1)
        self.ta2.setAutoFillBackground(True)
        self.ta2.setWindowTitle("")
        self.ta2.move(0, 0)
        self.ta2.resize(496, 423)
        self.ta2.setCursor(Qt.ArrowCursor)
        self.ta2.setToolTip("")
        self.custom_dns = QToolButton(self.ta2)
        self.custom_dns.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.custom_dns.setText("Connect To Custom")
        self.custom_dns.move(190, 370)
        self.custom_dns.resize(110, 42)
        self.custom_dns.setCursor(Qt.ArrowCursor)
        self.custom_dns.setToolTip("")
        self.custom_dns.clicked.connect(self.custom_dns_connect)
        self.beshkan_dns = QToolButton(self.ta2)
        self.beshkan_dns.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.beshkan_dns.setText("Connect To Beshkan")
        self.beshkan_dns.move(30, 120)
        self.beshkan_dns.resize(110, 42)
        self.beshkan_dns.setCursor(Qt.ArrowCursor)
        self.beshkan_dns.setToolTip("")
        self.beshkan_dns.clicked.connect(self.beshkan_dns_connect)
        self.Google_dns = QToolButton(self.ta2)
        self.Google_dns.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.Google_dns.setText("Connect To Google")
        self.Google_dns.move(30, 40)
        self.Google_dns.resize(110, 42)
        self.Google_dns.setCursor(Qt.ArrowCursor)
        self.Google_dns.setToolTip("")
        self.Google_dns.clicked.connect(self.google_dns_connect)
        self.label1 = QLabel(self.ta2)
        self.label1.setText("Google")
        self.label1.move(148, 36)
        self.label1.resize(40, 22)
        self.label1.setCursor(Qt.ArrowCursor)
        self.label1.setToolTip("")
        self.label2_copy = QLabel(self.ta2)
        self.label2_copy.setText("DNS : 8.8.8.4")
        self.label2_copy.move(290, 60)
        self.label2_copy.resize(90, 22)
        self.label2_copy.setCursor(Qt.ArrowCursor)
        self.label2_copy.setToolTip("")
        self.label2_copy_copy = QLabel(self.ta2)
        self.label2_copy_copy.setText("DNS : 8.8.8.8")
        self.label2_copy_copy.move(290, 40)
        self.label2_copy_copy.resize(90, 22)
        self.label2_copy_copy.setCursor(Qt.ArrowCursor)
        self.label2_copy_copy.setToolTip("")
        self.label3 = QLabel(self.ta2)
        self.label3.setText("Beshkan")
        self.label3.move(148, 116)
        self.label3.resize(90, 22)
        self.label3.setCursor(Qt.ArrowCursor)
        self.label3.setToolTip("")
        self.label4 = QLabel(self.ta2)
        self.label4.setText("Google Public DNS")
        self.label4.move(148, 56)
        self.label4.resize(90, 22)
        self.label4.setCursor(Qt.ArrowCursor)
        self.label4.setToolTip("")
        self.label5 = QLabel(self.ta2)
        self.label5.setText("Iranian Sanction Breaker")
        self.label5.move(148, 136)
        self.label5.resize(130, 22)
        self.label5.setCursor(Qt.ArrowCursor)
        self.label5.setToolTip("")
        self.label2_copy_copy_copy = QLabel(self.ta2)
        self.label2_copy_copy_copy.setText("DNS : 10.202.10.102")
        self.label2_copy_copy_copy.move(290, 130)
        self.label2_copy_copy_copy.resize(110, 22)
        self.label2_copy_copy_copy.setCursor(Qt.ArrowCursor)
        self.label2_copy_copy_copy.setToolTip("")
        self.label2_copy_copy_copy_copy = QLabel(self.ta2)
        self.label2_copy_copy_copy_copy.setText("DNS : 10.202.10.202")
        self.label2_copy_copy_copy_copy.move(290, 110)
        self.label2_copy_copy_copy_copy.resize(110, 22)
        self.label2_copy_copy_copy_copy.setCursor(Qt.ArrowCursor)
        self.label2_copy_copy_copy_copy.setToolTip("")
        self.custom_dns_entry = QLineEdit(self.ta2)
        self.custom_dns_entry.setText("")
        self.custom_dns_entry.move(138, 296)
        self.custom_dns_entry.resize(110, 22)
        self.custom_dns_entry.setCursor(Qt.IBeamCursor)
        self.custom_dns_entry.setToolTip("")
        self.label7 = QLabel(self.ta2)
        self.label7.setText("Enter Custom DNS")
        self.label7.move(28, 296)
        self.label7.resize(90, 22)
        self.label7.setCursor(Qt.ArrowCursor)
        self.label7.setToolTip("")
        self.label10 = QLabel(self.ta2)
        self.label10.setText("Adapter Name")
        self.label10.move(28, 336)
        self.label10.resize(90, 22)
        self.label10.setCursor(Qt.ArrowCursor)
        self.label10.setToolTip("")
        self.adapter_name_entry = QLineEdit(self.ta2)
        self.adapter_name_entry.setText("")
        self.adapter_name_entry.move(138, 336)
        self.adapter_name_entry.resize(110, 22)
        self.adapter_name_entry.setCursor(Qt.IBeamCursor)
        self.adapter_name_entry.setToolTip("")
        self.label11 = QLabel(self.ta2)
        self.label11.setText("Remember To Enter Adapter Name Inside Double Quotation")
        self.label11.move(98, 256)
        self.label11.resize(310, 22)
        self.label11.setCursor(Qt.ArrowCursor)
        self.label11.setToolTip("")
        self.show_adapters_button = QToolButton(self.ta2)
        self.show_adapters_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.show_adapters_button.setText("Show All Adapters")
        self.show_adapters_button.move(268, 316)
        self.show_adapters_button.resize(120, 22)
        self.show_adapters_button.setCursor(Qt.ArrowCursor)
        self.show_adapters_button.setToolTip("")
        self.show_adapters_button.clicked.connect(self.show_adapters)
        self.label12 = QLabel(self.ta2)
        self.label12.setText("or type ipconfig in cmd")
        self.label12.move(268, 336)
        self.label12.resize(120, 22)
        self.label12.setCursor(Qt.ArrowCursor)
        self.label12.setToolTip("")
        self.tab1.addTab(self.ta2, "DNS Changer")
        self.ta3 = QWidget(self.tab1)
        self.ta3.setAutoFillBackground(True)
        self.ta3.setWindowTitle("")
        self.ta3.move(0, 0)
        self.ta3.resize(496, 423)
        self.ta3.setCursor(Qt.ArrowCursor)
        self.ta3.setToolTip("")
        self.proxylistgrabber = QToolButton(self.ta3)
        self.proxylistgrabber.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.proxylistgrabber.setText("Grab Proxy List")
        self.proxylistgrabber.move(18, 336)
        self.proxylistgrabber.resize(160, 42)
        self.proxylistgrabber.setCursor(Qt.ArrowCursor)
        self.proxylistgrabber.setToolTip("")
        self.proxylistgrabber.clicked.connect(self.get_proxies)
        self.label13 = QLabel(self.ta3)
        self.label13.setText("Get Proxies")
        self.label13.move(28, 296)
        self.label13.resize(90, 22)
        self.label13.setCursor(Qt.ArrowCursor)
        self.label13.setToolTip("")
        self.label14 = QLabel(self.ta3)
        self.label14.setText("Grab Proxies From A Trusted Source")
        self.label14.move(18, 386)
        self.label14.resize(180, 22)
        self.label14.setCursor(Qt.ArrowCursor)
        self.label14.setToolTip("")
        self.generateandcheckproxy = QToolButton(self.ta3)
        self.generateandcheckproxy.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.generateandcheckproxy.setText("Generate And Check Proxies")
        self.generateandcheckproxy.move(288, 336)
        self.generateandcheckproxy.resize(160, 42)
        self.generateandcheckproxy.setCursor(Qt.ArrowCursor)
        self.generateandcheckproxy.setToolTip("")
        self.generateandcheckproxy.clicked.connect(self.openproxytools)
        self.label15 = QLabel(self.ta3)
        self.label15.setText("Choose This If Didnt Work")
        self.label15.move(298, 386)
        self.label15.resize(140, 22)
        self.label15.setCursor(Qt.ArrowCursor)
        self.label15.setToolTip("")
        self.ProxyList = QPlainTextEdit(self.ta3)
        self.ProxyList.setPlainText("")
        self.ProxyList.move(18, 36)
        self.ProxyList.resize(460, 260)
        self.ProxyList.setCursor(Qt.ArrowCursor)
        self.ProxyList.setToolTip("")
        self.label16 = QLabel(self.ta3)
        self.label16.setText("Proxies Appear Here")
        self.label16.move(28, 6)
        self.label16.resize(110, 22)
        self.label16.setCursor(Qt.ArrowCursor)
        self.label16.setToolTip("")
        self.tab1.addTab(self.ta3, "Proxy Connect")
        self.ta4 = QWidget(self.tab1)
        self.ta4.setAutoFillBackground(True)
        self.ta4.setWindowTitle("")
        self.ta4.move(0, 0)
        self.ta4.resize(496, 423)
        self.ta4.setCursor(Qt.ArrowCursor)
        self.ta4.setToolTip("")
        self.button5 = QToolButton(self.ta4)
        self.button5.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.button5.setText("Open UDP Flooder")
        self.button5.move(148, 286)
        self.button5.resize(190, 72)
        self.button5.setCursor(Qt.ArrowCursor)
        self.button5.setToolTip("")
        self.button5.clicked.connect(self.ddos)
        self.tab1.addTab(self.ta4, "DDOS")
        self.ta5 = QWidget(self.tab1)
        self.ta5.setAutoFillBackground(True)
        self.ta5.setWindowTitle("")
        self.ta5.move(0, 0)
        self.ta5.resize(496, 423)
        self.ta5.setCursor(Qt.ArrowCursor)
        self.ta5.setToolTip("")
        self.button6 = QToolButton(self.ta5)
        self.button6.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.button6.setText("Proxy Connect")
        self.button6.move(28, 16)
        self.button6.resize(200, 92)
        self.button6.setCursor(Qt.ArrowCursor)
        self.button6.setToolTip("")
        self.button6.clicked.connect(self.proxytool)
        self.button7 = QToolButton(self.ta5)
        self.button7.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.button7.setText("Mac Address Change")
        self.button7.move(258, 16)
        self.button7.resize(200, 92)
        self.button7.setCursor(Qt.ArrowCursor)
        self.button7.setToolTip("")
        self.button7.clicked.connect(self.macchange)
        self.button8 = QToolButton(self.ta5)
        self.button8.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.button8.setText("OpenVPN Connect")
        self.button8.move(28, 136)
        self.button8.resize(200, 92)
        self.button8.setCursor(Qt.ArrowCursor)
        self.button8.setToolTip("")
        self.button8.clicked.connect(self.openvpn)
        self.tab1.addTab(self.ta5, "Utilities")
        self.ta6 = QWidget(self.tab1)
        self.ta6.setAutoFillBackground(True)
        self.ta6.setWindowTitle("")
        self.ta6.move(0, 0)
        self.ta6.resize(496, 423)
        self.ta6.setCursor(Qt.ArrowCursor)
        self.ta6.setToolTip("")
        self.label22 = QLabel(self.ta6)
        self.label22.setText("my name is mohamad hani janaty and im 16 years old")
        self.label22.move(28, 26)
        self.label22.resize(270, 22)
        self.label22.setCursor(Qt.ArrowCursor)
        self.label22.setToolTip("")
        self.label23 = QLabel(self.ta6)
        self.label23.setText("you can find my other works in my github page")
        self.label23.move(28, 46)
        self.label23.resize(230, 22)
        self.label23.setCursor(Qt.ArrowCursor)
        self.label23.setToolTip("")
        self.label24 = QLabel(self.ta6)
        self.label24.setText("Github : github.com/hanicraft")
        self.label24.move(28, 226)
        self.label24.resize(150, 22)
        self.label24.setCursor(Qt.ArrowCursor)
        self.label24.setToolTip("")
        self.label25 = QLabel(self.ta6)
        self.label25.setText("Instagram : mohamadhanijanaty85")
        self.label25.move(28, 246)
        self.label25.resize(180, 22)
        self.label25.setCursor(Qt.ArrowCursor)
        self.label25.setToolTip("")
        self.label26 = QLabel(self.ta6)
        self.label26.setText("Reddit : u/mhjhacker1")
        self.label26.move(28, 266)
        self.label26.resize(120, 22)
        self.label26.setCursor(Qt.ArrowCursor)
        self.label26.setToolTip("")
        self.label27 = QLabel(self.ta6)
        self.label27.setText("Itch : mohamadhanijanaty85")
        self.label27.move(28, 286)
        self.label27.resize(150, 22)
        self.label27.setCursor(Qt.ArrowCursor)
        self.label27.setToolTip("")
        self.tab1.addTab(self.ta6, "About")
        return self.w1

    def google_dns_connect(self):
        os.system("""netsh interface ip set dns "Local Area Connection" static 8.8.8.8""")

    def beshkan_dns_connect(self):
        os.system("""netsh interface ip set dns "Local Area Connection" static 10.202.10.202""")

    def custom_dns_connect(self):
        self.dns = self.custom_dns_entry.text() 
        self.adapter = self.adapter_name_entry.text()
        os.system("netsh interface ip set dns name=" + self.adapter + " static " + self.dns)

    def show_adapters(self):
        adapters = []
        for interface in netifaces.interfaces():
            adapters.append(interface)
        if adapters:
            message = "Available network adapters:\n\n" + "\n".join(adapters)
        else:
            message = "No network adapters found."
        msg_box = QMessageBox()
        msg_box.setText(message)
        msg_box.exec_()

    def get_proxies(self):
        self.proxies = []
        url = "https://api.getproxylist.com/proxy"
        response = requests.get(url)
        if response.status_code == 200:
            self.proxies.append(response.json())
            self.ProxyList.setText("Proxies retrieved: {}".format(len(self.proxies)))

    def openproxytools(self):
        os.system("ProxyGenerator.exe")
        msgbox2 = QMessageBox()
        msgbox2.setText("proxy generator has been opened. please see your terminal/cmd")
        msgbox2.exec_()

    def ddos(self):
        os.system("python DDOS.py")

    def proxytool(self):
        os.system("python proxyconnect.py")

    def macchange(self):
        os.system("python macchange.py")

    def openvpn(self):
        os.system("python openvpn.py")
    
if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    a = Widget1()
    a.show()
    sys.exit(app.exec_())